app = "trickfirediscordbot"
primary_region = "sea"

[http_service]
auto_start_machines = true
force_https = true
internal_port = 8_080
min_machines_running = 0
processes = [ "app" ]

[[mounts]]
destination = "/data"
source = "data"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "512mb"